"""Reporter module for generating pipeline health summaries."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional

from pipewatch.core.monitor import Monitor
from pipewatch.core.pipeline import PipelineStatus
from pipewatch.core.alert import AlertLevel


@dataclass
class PipelineSummary:
    """Summary of a single pipeline's health."""
    name: str
    status: str
    total_checks: int
    passed_checks: int
    failed_checks: int
    active_alerts: List[dict] = field(default_factory=list)

    @property
    def health_score(self) -> float:
        """Return a health score between 0.0 and 1.0."""
        if self.total_checks == 0:
            return 1.0
        return self.passed_checks / self.total_checks


@dataclass
class Report:
    """Full health report generated by the Reporter."""
    generated_at: str
    total_pipelines: int
    healthy_pipelines: int
    degraded_pipelines: int
    failed_pipelines: int
    summaries: List[PipelineSummary] = field(default_factory=list)
    critical_alerts: int = 0

    def to_dict(self) -> dict:
        return {
            "generated_at": self.generated_at,
            "total_pipelines": self.total_pipelines,
            "healthy_pipelines": self.healthy_pipelines,
            "degraded_pipelines": self.degraded_pipelines,
            "failed_pipelines": self.failed_pipelines,
            "critical_alerts": self.critical_alerts,
            "summaries": [
                {
                    "name": s.name,
                    "status": s.status,
                    "health_score": round(s.health_score, 2),
                    "total_checks": s.total_checks,
                    "passed_checks": s.passed_checks,
                    "failed_checks": s.failed_checks,
                    "active_alerts": s.active_alerts,
                }
                for s in self.summaries
            ],
        }


class Reporter:
    """Generates health reports from a Monitor instance."""

    def __init__(self, monitor: Monitor):
        self.monitor = monitor

    def generate(self) -> Report:
        """Generate a full health report from the current monitor state."""
        summaries = []
        healthy = degraded = failed = 0
        critical_alerts = 0

        for pipeline in self.monitor.pipelines.values():
            checks = pipeline.checks
            passed = sum(1 for c in checks if c.status.value == "pass")
            total = len(checks)
            failed_count = sum(1 for c in checks if c.status.value == "fail")

            active_alerts = [
                a.to_dict() for a in pipeline.alerts if not a.resolved
            ]
            critical_alerts += sum(
                1 for a in pipeline.alerts
                if not a.resolved and a.level == AlertLevel.CRITICAL
            )

            summary = PipelineSummary(
                name=pipeline.name,
                status=pipeline.status.value,
                total_checks=total,
                passed_checks=passed,
                failed_checks=failed_count,
                active_alerts=active_alerts,
            )
            summaries.append(summary)

            if pipeline.status == PipelineStatus.HEALTHY:
                healthy += 1
            elif pipeline.status == PipelineStatus.DEGRADED:
                degraded += 1
            else:
                failed += 1

        return Report(
            generated_at=datetime.utcnow().isoformat(),
            total_pipelines=len(summaries),
            healthy_pipelines=healthy,
            degraded_pipelines=degraded,
            failed_pipelines=failed,
            summaries=summaries,
            critical_alerts=critical_alerts,
        )
